"""add company and source to lead

Revision ID: 32d548189f0b
Revises: c8d5664fb3e9
Create Date: 2026-08-23 12:37:27.603551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d548189f0b'
down_revision: Union[str, Sequence[str], None] = 'c8d5664fb3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(), nullable=False, server_default='unknown'))
        batch_op.add_column(sa.Column('source', sa.String(), nullable=False, server_default='other'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
